spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: sellergoods-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9001

