spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: sellergoods-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
server:
  port: 9006
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
feign:
  hystrix:
    enabled: true
#tm:
#  manager:
#    url: http://127.0.0.1:8899/tx/manager/