server:
  port: 9999

spring:
  application:
    name: pinyougou-gateway
  cloud:
    gateway:
      routes:
      - id: apisellergoods
        uri: lb://sellergoods-service
        predicates:
        - Path=/apisellergoods/**
        filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      - id: apiorder
        uri: lb://order-service
        predicates:
        - Path=/apiorder/**
        filters:
         - StripPrefix=1
         - name: Hystrix
           args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/