server:
  port: 9999

spring:
  application:
    name: pinyougou-gateway
  cloud:
    gateway:
      routes:
      - id: apisellergoods
        uri: lb://sellergoods-service
        predicates:
        - Path=/apisellergoods/**
        filters:
        - StripPrefix=1
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
#重点！/info必须使用http进行转发，lb代表从注册中心获取服务
# 重点！转发该路径！,/apisellergoods/**,
# http://localhost:9999/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
#而不是我们期望的去掉userapi，只保留**部分
#-name Hystrix gateWay整合hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/